import dotenv from "dotenv";

dotenv.config();

export const {
  PORT,
  MONGODB_URL,
  MESSAGE_BROKER_URL,
  PROFILE_SERVICE_URL,
  SENDER_EMAIL,
  CLIENT_URL,
  JWT_EMAIL_VERIFICATION_KEY,
  JWT_AUTHENTICATION_KEY,
  JWT_RESET_PASSWORD_KEY,
  JWT_RESET_PASSWORD_EXPIRES_IN,
  JWT_AUTHENTICATION_EXPIRES_IN,
  AUTH_SERVICE_VERIFICATION_KEY,
  GATEWAY_VERIFICATION_KEY
} = process.env;
