apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-redis
spec:
  selector:
    matchLabels:
      app: JobTH
      kind: db
      db: redis
      service: api-gateway
  template:
    metadata:
      labels:
        app: JobTH
        kind: db
        db: redis
        service: api-gateway
    spec:
      containers:
        - name: api-gateway-redis
          image: redis
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-redis-service
spec:
  selector:
    app: JobTH
    kind: db
    db: redis
    service: api-gateway
  ports:
    - port: 6379
      targetPort: 6379
