export const Queues = {
  AUTH_PROFILE_ROLLED_BACK: "AUTH.PROFILE.ROLLED-BACK",
  AUTH_PROFILE_ROLLED_BACK_DEAD: "AUTH.PROFILE.ROLLED-BACK.DEAD",
};

export const MessageTypes = {
  JOB_SEEKER_ROLLED_BACK: "JOB_SEEKER_ROLLED_BACK",
  COMPANY_ROLLED_BACK: "COMPANY_ROLLED_BACK"
}