apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobs-searching-service-elasticsearch-pv
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath: 
    path: /data
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobs-searching-service-elasticsearch-pvc
spec:
  resources:
    requests:
      storage: 50Mi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce