import dotenv from "dotenv";

dotenv.config();

export const {
  PORT,
  MONGODB_URL,
  MESSAGE_BROKER_URL,
  APPLICATIONS_SERVICE_URL,
  JOBS_SEARCHING_SERVICE_URL,
  CLIENT_URL,
  GATEWAY_VERIFICATION_KEY,
  AUTH_SERVICE_VERIFICATION_KEY,
  JOBS_SERVICE_VERIFICATION_KEY,
} = process.env;
