import dotenv from "dotenv";

dotenv.config();

export const {
  PORT,
  MONGODB_URL,
  MESSAGE_BROKER_URL,
  JOBS_SERVICE_URL,
  JOBS_SEARCHING_SERVICE_URL,
  CLIENT_URL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  JWT_AUTHENTICATION_KEY,
  GATEWAY_VERIFICATION_KEY,
  AUTH_SERVICE_VERIFICATION_KEY,
  PROFILE_SERVICE_VERIFICATION_KEY,
} = process.env;
